/* The following code was generated by JFlex 1.4.3 on 6/12/14 1:46 PM */

package org.intellij.yang.lexer;
import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static org.intellij.yang.psi.YangTypes.*;
import static org.intellij.yang.psi.YangTokenTypeSets.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/12/14 1:46 PM from the specification file
 * <tt>/Users/dave/dev/yang/src/org/intellij/yang/lexer/_YangLexer.flex</tt>
 */
public class _YangLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\12"+
    "\4\0\1\0\2\0\1\5\1\6\1\0\1\13\1\7\1\4\1\7"+
    "\7\7\2\7\1\14\1\15\5\0\6\7\24\7\1\0\1\11\2\0"+
    "\1\43\1\0\1\20\1\32\1\36\1\41\1\30\1\40\1\26\1\37"+
    "\1\35\1\7\1\45\1\24\1\23\1\21\1\34\1\42\1\47\1\25"+
    "\1\33\1\31\1\27\1\44\1\50\1\10\1\22\1\46\1\16\1\0"+
    "\1\17\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\3\1\1\1\5"+
    "\1\6\1\7\25\3\4\0\60\3\2\10\2\0\3\3"+
    "\1\11\21\3\1\12\11\3\1\13\27\3\1\14\1\3"+
    "\1\0\1\10\11\3\1\15\2\3\1\16\1\3\1\17"+
    "\11\3\1\20\1\3\1\21\1\3\1\22\1\23\13\3"+
    "\1\24\12\3\1\25\4\3\1\26\15\3\1\27\6\3"+
    "\1\30\13\3\1\31\20\3\1\32\1\33\10\3\1\34"+
    "\2\3\1\35\1\3\1\36\4\3\1\37\5\3\1\40"+
    "\2\3\1\41\1\3\1\42\4\3\1\43\1\44\2\3"+
    "\1\45\5\3\1\46\2\3\1\47\11\3\1\50\6\3"+
    "\1\51\4\3\1\52\3\3\1\53\1\3\1\54\1\3"+
    "\1\55\1\56\1\3\1\57\2\3\1\60\11\3\1\61"+
    "\1\3\1\62\10\3\1\63\4\3\1\64\1\65\1\66"+
    "\4\3\1\67\1\3\1\70\1\71\2\3\1\72\3\3"+
    "\1\73\3\3\1\74\2\3\1\75\11\3\1\76\1\3"+
    "\1\77\1\100\4\3\1\101\10\3\1\102\1\103\1\104"+
    "\1\105\1\106\4\3\1\107\1\3\1\110\1\3\1\111"+
    "\1\112\4\3\1\113\1\114";

  private static int [] zzUnpackAction() {
    int [] result = new int[436];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\51\0\244\0\315\0\51"+
    "\0\51\0\51\0\366\0\u011f\0\u0148\0\u0171\0\u019a\0\u01c3"+
    "\0\u01ec\0\u0215\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2\0\u030b"+
    "\0\u0334\0\u035d\0\u0386\0\u03af\0\u03d8\0\u0401\0\u042a\0\u0453"+
    "\0\u047c\0\315\0\u04a5\0\51\0\u04ce\0\u04f7\0\u0520\0\u0549"+
    "\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u0616\0\u063f\0\u0668\0\u0691"+
    "\0\u06ba\0\u06e3\0\u070c\0\u0735\0\u075e\0\u0787\0\u07b0\0\u07d9"+
    "\0\u0802\0\u082b\0\u0854\0\u087d\0\u08a6\0\u08cf\0\u08f8\0\u0921"+
    "\0\u094a\0\u0973\0\u099c\0\u09c5\0\u09ee\0\u0a17\0\u0a40\0\u0a69"+
    "\0\u0a92\0\u0abb\0\u0ae4\0\u0b0d\0\u0b36\0\u0b5f\0\u0b88\0\u0bb1"+
    "\0\u0bda\0\u0c03\0\u0c2c\0\u0c55\0\51\0\u0c7e\0\u0ca7\0\u0cd0"+
    "\0\u0cf9\0\u0d22\0\244\0\u0d4b\0\u0d74\0\u0d9d\0\u0dc6\0\u0def"+
    "\0\u0e18\0\u0e41\0\u0e6a\0\u0e93\0\u0ebc\0\u0ee5\0\u0f0e\0\u0f37"+
    "\0\u0f60\0\u0f89\0\u0fb2\0\u0fdb\0\244\0\u1004\0\u102d\0\u1056"+
    "\0\u107f\0\u10a8\0\u10d1\0\u10fa\0\u1123\0\u114c\0\244\0\u1175"+
    "\0\u119e\0\u11c7\0\u11f0\0\u1219\0\u1242\0\u126b\0\u1294\0\u12bd"+
    "\0\u12e6\0\u130f\0\u1338\0\u1361\0\u138a\0\u13b3\0\u13dc\0\u1405"+
    "\0\u142e\0\u1457\0\u1480\0\u14a9\0\u14d2\0\u14fb\0\244\0\u1524"+
    "\0\u154d\0\u0c7e\0\u1576\0\u159f\0\u15c8\0\u15f1\0\u161a\0\u1643"+
    "\0\u166c\0\u1695\0\u16be\0\244\0\u16e7\0\u1710\0\u1739\0\u1762"+
    "\0\244\0\u178b\0\u17b4\0\u17dd\0\u1806\0\u182f\0\u1858\0\u1881"+
    "\0\u18aa\0\u18d3\0\244\0\u18fc\0\244\0\u1925\0\u194e\0\244"+
    "\0\u1977\0\u19a0\0\u19c9\0\u19f2\0\u1a1b\0\u1a44\0\u1a6d\0\u1a96"+
    "\0\u1abf\0\u1ae8\0\u1b11\0\244\0\u1b3a\0\u1b63\0\u1b8c\0\u1bb5"+
    "\0\u1bde\0\u1c07\0\u1c30\0\u1c59\0\u1c82\0\u1cab\0\244\0\u1cd4"+
    "\0\u1cfd\0\u1d26\0\u1d4f\0\244\0\u1d78\0\u1da1\0\u1dca\0\u1df3"+
    "\0\u1e1c\0\u1e45\0\u1e6e\0\u1e97\0\u1ec0\0\u1ee9\0\u1f12\0\u1f3b"+
    "\0\u1f64\0\244\0\u1f8d\0\u1fb6\0\u1fdf\0\u2008\0\u2031\0\u205a"+
    "\0\244\0\u2083\0\u20ac\0\u20d5\0\u20fe\0\u2127\0\u2150\0\u2179"+
    "\0\u21a2\0\u21cb\0\u21f4\0\u221d\0\244\0\u2246\0\u226f\0\u2298"+
    "\0\u22c1\0\u22ea\0\u2313\0\u233c\0\u2365\0\u238e\0\u23b7\0\u23e0"+
    "\0\u2409\0\u2432\0\u245b\0\u2484\0\u24ad\0\244\0\244\0\u24d6"+
    "\0\u24ff\0\u2528\0\u2551\0\u257a\0\u25a3\0\u25cc\0\u25f5\0\244"+
    "\0\u261e\0\u2647\0\244\0\u2670\0\244\0\u2699\0\u26c2\0\u26eb"+
    "\0\u2714\0\244\0\u273d\0\u2766\0\u278f\0\u27b8\0\u27e1\0\244"+
    "\0\u280a\0\u2833\0\244\0\u285c\0\244\0\u2885\0\u28ae\0\u28d7"+
    "\0\u2900\0\244\0\244\0\u2929\0\u2952\0\244\0\u297b\0\u29a4"+
    "\0\u29cd\0\u29f6\0\u2a1f\0\244\0\u2a48\0\u2a71\0\244\0\u2a9a"+
    "\0\u2ac3\0\u2aec\0\u2b15\0\u2b3e\0\u2b67\0\u2b90\0\u2bb9\0\u2be2"+
    "\0\244\0\u2c0b\0\u2c34\0\u2c5d\0\u2c86\0\u2caf\0\u2cd8\0\244"+
    "\0\u2d01\0\u2d2a\0\u2d53\0\u2d7c\0\244\0\u2da5\0\u2dce\0\u2df7"+
    "\0\244\0\u2e20\0\244\0\u2e49\0\244\0\244\0\u2e72\0\244"+
    "\0\u2e9b\0\u2ec4\0\244\0\u2eed\0\u2f16\0\u2f3f\0\u2f68\0\u2f91"+
    "\0\u2fba\0\u2fe3\0\u300c\0\u3035\0\u305e\0\u3087\0\244\0\u30b0"+
    "\0\u30d9\0\u3102\0\u312b\0\u3154\0\u317d\0\u31a6\0\u31cf\0\244"+
    "\0\u31f8\0\u3221\0\u324a\0\u3273\0\244\0\244\0\244\0\u329c"+
    "\0\u32c5\0\u32ee\0\u3317\0\244\0\u3340\0\244\0\244\0\u3369"+
    "\0\u3392\0\244\0\u33bb\0\u33e4\0\u340d\0\244\0\u3436\0\u345f"+
    "\0\u3488\0\244\0\u34b1\0\u34da\0\244\0\u3503\0\u352c\0\u3555"+
    "\0\u357e\0\u35a7\0\u35d0\0\u35f9\0\u3622\0\u364b\0\244\0\u3674"+
    "\0\244\0\244\0\u369d\0\u36c6\0\u36ef\0\u3718\0\244\0\u3741"+
    "\0\u376a\0\u3793\0\u37bc\0\u37e5\0\u380e\0\u3837\0\u3860\0\244"+
    "\0\244\0\244\0\244\0\244\0\u3889\0\u38b2\0\u38db\0\u3904"+
    "\0\244\0\u392d\0\244\0\u3956\0\244\0\244\0\u397f\0\u39a8"+
    "\0\u39d1\0\u39fa\0\244\0\244";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[436];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\2\1\5\2\6\1\2\1\7"+
    "\1\6\1\2\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\6\1\32\1\33\1\34"+
    "\1\6\1\35\1\36\2\6\1\37\52\0\3\3\51\0"+
    "\1\40\1\41\1\0\2\6\2\0\2\6\3\0\31\6"+
    "\7\0\2\6\2\0\2\6\3\0\31\6\11\42\1\43"+
    "\1\44\36\42\7\0\2\6\2\0\2\6\3\0\1\6"+
    "\1\45\3\6\1\46\1\6\1\47\11\6\1\50\7\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\51\13\6\1\52"+
    "\14\6\7\0\2\6\2\0\2\6\3\0\1\53\14\6"+
    "\1\54\13\6\7\0\2\6\2\0\2\6\3\0\1\55"+
    "\6\6\1\56\4\6\1\57\1\60\13\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\61\4\6\1\62\13\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\63\7\6\1\64"+
    "\11\6\1\65\6\6\7\0\2\6\2\0\2\6\3\0"+
    "\5\6\1\66\23\6\7\0\2\6\2\0\2\6\3\0"+
    "\1\6\1\67\11\6\1\70\15\6\7\0\1\6\1\71"+
    "\2\0\2\6\3\0\1\6\1\72\3\6\1\73\23\6"+
    "\7\0\2\6\2\0\2\6\3\0\2\6\1\74\26\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\75\7\6\1\76"+
    "\4\6\1\77\13\6\7\0\2\6\2\0\2\6\3\0"+
    "\7\6\1\100\1\6\1\101\17\6\7\0\2\6\2\0"+
    "\2\6\3\0\5\6\1\102\1\6\1\103\21\6\7\0"+
    "\2\6\2\0\2\6\3\0\1\6\1\104\1\6\1\105"+
    "\14\6\1\106\1\107\7\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\110\13\6\1\111\2\6\1\112\11\6\7\0"+
    "\2\6\2\0\2\6\3\0\5\6\1\113\2\6\1\114"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\10\6\1\115"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\1\116\4\6"+
    "\1\117\6\6\1\120\14\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\121\30\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\122\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\17\6\1\123\11\6\1\40\1\124\1\125\46\40\5\126"+
    "\1\127\43\126\51\42\7\0\2\6\2\0\2\6\3\0"+
    "\2\6\1\130\26\6\7\0\2\6\2\0\2\6\3\0"+
    "\6\6\1\131\22\6\7\0\2\6\2\0\2\6\3\0"+
    "\6\6\1\132\22\6\7\0\2\6\2\0\2\6\3\0"+
    "\21\6\1\133\7\6\7\0\2\6\2\0\2\6\3\0"+
    "\3\6\1\134\25\6\7\0\2\6\2\0\2\6\3\0"+
    "\11\6\1\135\17\6\7\0\2\6\2\0\2\6\3\0"+
    "\1\6\1\136\27\6\7\0\2\6\2\0\2\6\3\0"+
    "\1\6\1\137\27\6\7\0\1\6\1\140\2\0\2\6"+
    "\3\0\1\6\1\141\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\13\6\1\142\15\6\7\0\2\6\2\0\2\6"+
    "\3\0\21\6\1\143\7\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\6\1\144\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\145\1\146\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\13\6\1\147\15\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\6\1\150\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\20\6\1\151\1\6\1\152\1\6\1\153\2\6"+
    "\1\154\1\6\7\0\2\6\2\0\2\6\3\0\16\6"+
    "\1\155\12\6\7\0\2\6\2\0\2\6\3\0\14\6"+
    "\1\156\14\6\7\0\2\6\2\0\2\6\3\0\15\6"+
    "\1\157\13\6\7\0\2\6\2\0\2\6\3\0\10\6"+
    "\1\160\20\6\7\0\2\6\2\0\2\6\3\0\11\6"+
    "\1\161\17\6\7\0\2\6\2\0\2\6\3\0\7\6"+
    "\1\162\21\6\7\0\2\6\2\0\2\6\3\0\5\6"+
    "\1\163\23\6\7\0\2\6\2\0\2\6\3\0\22\6"+
    "\1\164\6\6\7\0\2\6\2\0\2\6\3\0\13\6"+
    "\1\165\15\6\7\0\2\6\2\0\2\6\3\0\4\6"+
    "\1\166\24\6\7\0\2\6\2\0\2\6\3\0\11\6"+
    "\1\167\17\6\7\0\2\6\2\0\2\6\3\0\12\6"+
    "\1\170\16\6\7\0\2\6\2\0\2\6\3\0\1\171"+
    "\30\6\7\0\2\6\2\0\2\6\3\0\6\6\1\172"+
    "\12\6\1\173\7\6\7\0\2\6\2\0\2\6\3\0"+
    "\11\6\1\174\17\6\7\0\2\6\2\0\2\6\3\0"+
    "\16\6\1\175\3\6\1\176\6\6\7\0\2\6\2\0"+
    "\2\6\3\0\22\6\1\177\6\6\7\0\2\6\2\0"+
    "\1\200\1\6\3\0\31\6\7\0\2\6\2\0\2\6"+
    "\3\0\10\6\1\201\20\6\7\0\2\6\2\0\2\6"+
    "\3\0\13\6\1\202\15\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\6\1\203\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\14\6\1\204\14\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\205\30\6\7\0\2\6\2\0\2\6\3\0"+
    "\1\206\30\6\7\0\2\6\2\0\2\6\3\0\4\6"+
    "\1\207\6\6\1\210\4\6\1\211\3\6\1\212\4\6"+
    "\7\0\2\6\2\0\2\6\3\0\11\6\1\213\17\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\214\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\13\6\1\215\15\6"+
    "\7\0\2\6\2\0\2\6\3\0\4\6\1\216\24\6"+
    "\7\0\2\6\2\0\2\6\3\0\2\6\1\217\26\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\220\20\6"+
    "\2\0\1\125\46\0\5\126\1\221\47\126\1\222\1\221"+
    "\43\126\7\0\1\6\1\223\2\0\2\6\3\0\31\6"+
    "\7\0\2\6\2\0\2\6\3\0\7\6\1\224\21\6"+
    "\7\0\2\6\2\0\2\6\3\0\3\6\1\225\25\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\226\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\15\6\1\227\13\6"+
    "\7\0\2\6\2\0\2\6\3\0\6\6\1\230\22\6"+
    "\7\0\2\6\2\0\1\231\1\6\3\0\31\6\7\0"+
    "\2\6\2\0\1\232\1\6\3\0\31\6\7\0\2\6"+
    "\2\0\2\6\3\0\21\6\1\233\7\6\7\0\2\6"+
    "\2\0\2\6\3\0\11\6\1\234\17\6\7\0\2\6"+
    "\2\0\2\6\3\0\7\6\1\235\21\6\7\0\2\6"+
    "\2\0\1\236\1\6\3\0\31\6\7\0\2\6\2\0"+
    "\2\6\3\0\20\6\1\237\10\6\7\0\2\6\2\0"+
    "\2\6\3\0\6\6\1\240\22\6\7\0\2\6\2\0"+
    "\2\6\3\0\11\6\1\241\17\6\7\0\2\6\2\0"+
    "\2\6\3\0\6\6\1\242\22\6\7\0\2\6\2\0"+
    "\2\6\3\0\10\6\1\243\4\6\1\244\13\6\7\0"+
    "\2\6\2\0\2\6\3\0\4\6\1\245\24\6\7\0"+
    "\2\6\2\0\2\6\3\0\15\6\1\246\13\6\7\0"+
    "\2\6\2\0\2\6\3\0\7\6\1\247\21\6\7\0"+
    "\2\6\2\0\2\6\3\0\7\6\1\250\21\6\7\0"+
    "\2\6\2\0\2\6\3\0\11\6\1\251\15\6\1\252"+
    "\1\6\7\0\2\6\2\0\2\6\3\0\13\6\1\253"+
    "\15\6\7\0\2\6\2\0\2\6\3\0\10\6\1\254"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\3\6\1\255"+
    "\25\6\7\0\2\6\2\0\2\6\3\0\14\6\1\256"+
    "\14\6\7\0\2\6\2\0\2\6\3\0\10\6\1\257"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\10\6\1\260"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\14\6\1\261"+
    "\14\6\7\0\2\6\2\0\2\6\3\0\3\6\1\262"+
    "\25\6\7\0\2\6\2\0\2\6\3\0\11\6\1\263"+
    "\17\6\7\0\2\6\2\0\2\6\3\0\1\264\30\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\265\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\22\6\1\266\6\6"+
    "\7\0\2\6\2\0\2\6\3\0\4\6\1\267\24\6"+
    "\7\0\2\6\2\0\2\6\3\0\7\6\1\270\21\6"+
    "\7\0\2\6\2\0\2\6\3\0\14\6\1\271\14\6"+
    "\7\0\2\6\2\0\2\6\3\0\20\6\1\272\10\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\6\1\273\27\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\274\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\11\6\1\275\6\6"+
    "\1\276\10\6\7\0\2\6\2\0\2\6\3\0\15\6"+
    "\1\277\13\6\7\0\2\6\2\0\2\6\3\0\16\6"+
    "\1\300\12\6\7\0\2\6\2\0\2\6\3\0\11\6"+
    "\1\301\17\6\7\0\2\6\2\0\2\6\3\0\10\6"+
    "\1\302\20\6\7\0\2\6\2\0\2\6\3\0\16\6"+
    "\1\303\12\6\7\0\2\6\2\0\2\6\3\0\1\304"+
    "\30\6\7\0\2\6\2\0\2\6\3\0\15\6\1\305"+
    "\13\6\7\0\2\6\2\0\2\6\3\0\11\6\1\306"+
    "\5\6\1\307\11\6\7\0\2\6\2\0\2\6\3\0"+
    "\13\6\1\310\4\6\1\311\10\6\7\0\2\6\2\0"+
    "\2\6\3\0\15\6\1\312\13\6\7\0\2\6\2\0"+
    "\2\6\3\0\7\6\1\313\21\6\7\0\2\6\2\0"+
    "\2\6\3\0\1\6\1\314\27\6\4\126\1\125\1\221"+
    "\43\126\7\0\2\6\2\0\2\6\3\0\3\6\1\315"+
    "\25\6\7\0\2\6\2\0\2\6\3\0\3\6\1\316"+
    "\25\6\7\0\2\6\2\0\2\6\3\0\10\6\1\317"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\13\6\1\320"+
    "\15\6\7\0\2\6\2\0\2\6\3\0\20\6\1\321"+
    "\10\6\7\0\2\6\2\0\1\322\1\6\3\0\31\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\323\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\324\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\325\30\6\7\0"+
    "\2\6\2\0\2\6\3\0\4\6\1\326\24\6\7\0"+
    "\2\6\2\0\2\6\3\0\10\6\1\327\20\6\7\0"+
    "\2\6\2\0\1\330\1\6\3\0\31\6\7\0\2\6"+
    "\2\0\2\6\3\0\11\6\1\331\17\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\332\20\6\7\0\2\6"+
    "\2\0\2\6\3\0\5\6\1\333\23\6\7\0\2\6"+
    "\2\0\2\6\3\0\1\6\1\334\27\6\7\0\2\6"+
    "\2\0\2\6\3\0\1\335\30\6\7\0\2\6\2\0"+
    "\2\6\3\0\13\6\1\336\15\6\7\0\2\6\2\0"+
    "\2\6\3\0\15\6\1\337\13\6\7\0\2\6\2\0"+
    "\2\6\3\0\22\6\1\340\6\6\7\0\2\6\2\0"+
    "\2\6\3\0\13\6\1\341\15\6\7\0\2\6\2\0"+
    "\2\6\3\0\7\6\1\342\21\6\7\0\2\6\2\0"+
    "\2\6\3\0\1\6\1\343\27\6\7\0\2\6\2\0"+
    "\2\6\3\0\5\6\1\344\23\6\7\0\2\6\2\0"+
    "\2\6\3\0\21\6\1\345\7\6\7\0\2\6\2\0"+
    "\2\6\3\0\1\6\1\346\27\6\7\0\2\6\2\0"+
    "\2\6\3\0\14\6\1\347\14\6\7\0\2\6\2\0"+
    "\2\6\3\0\7\6\1\350\21\6\7\0\2\6\2\0"+
    "\2\6\3\0\1\6\1\351\27\6\7\0\2\6\2\0"+
    "\2\6\3\0\5\6\1\352\23\6\7\0\2\6\2\0"+
    "\2\6\3\0\7\6\1\353\21\6\7\0\2\6\2\0"+
    "\2\6\3\0\7\6\1\354\21\6\7\0\2\6\2\0"+
    "\2\6\3\0\11\6\1\355\17\6\7\0\2\6\2\0"+
    "\2\6\3\0\5\6\1\356\23\6\7\0\2\6\2\0"+
    "\2\6\3\0\10\6\1\357\20\6\7\0\2\6\2\0"+
    "\2\6\3\0\11\6\1\360\17\6\7\0\2\6\2\0"+
    "\2\6\3\0\1\361\30\6\7\0\2\6\2\0\2\6"+
    "\3\0\15\6\1\362\13\6\7\0\2\6\2\0\2\6"+
    "\3\0\16\6\1\363\12\6\7\0\2\6\2\0\2\6"+
    "\3\0\11\6\1\364\17\6\7\0\2\6\2\0\2\6"+
    "\3\0\7\6\1\365\21\6\7\0\2\6\2\0\2\6"+
    "\3\0\11\6\1\366\17\6\7\0\2\6\2\0\2\6"+
    "\3\0\5\6\1\367\23\6\7\0\2\6\2\0\2\6"+
    "\3\0\7\6\1\370\21\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\371\30\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\372\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\373\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\15\6\1\374\13\6\7\0\2\6\2\0\2\6\3\0"+
    "\11\6\1\375\17\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\376\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\4\6\1\377\24\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\u0100\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\1\6\1\u0101\27\6\7\0\2\6\2\0\2\6\3\0"+
    "\22\6\1\u0102\6\6\7\0\2\6\2\0\2\6\3\0"+
    "\15\6\1\u0103\13\6\7\0\2\6\2\0\2\6\3\0"+
    "\24\6\1\u0104\4\6\7\0\2\6\2\0\2\6\3\0"+
    "\4\6\1\u0105\24\6\7\0\2\6\2\0\2\6\3\0"+
    "\4\6\1\u0106\24\6\7\0\2\6\2\0\2\6\3\0"+
    "\11\6\1\u0107\17\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\u0108\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\4\6\1\u0109\24\6\7\0\2\6\2\0\2\6\3\0"+
    "\4\6\1\u010a\24\6\7\0\2\6\2\0\2\6\3\0"+
    "\17\6\1\u010b\11\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\u010c\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\u010d\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\16\6\1\u010e\12\6\7\0\2\6\2\0\2\6\3\0"+
    "\15\6\1\u010f\13\6\7\0\2\6\2\0\2\6\3\0"+
    "\5\6\1\u0110\23\6\7\0\2\6\2\0\2\6\3\0"+
    "\15\6\1\u0111\13\6\7\0\2\6\2\0\2\6\3\0"+
    "\10\6\1\u0112\20\6\7\0\2\6\2\0\2\6\3\0"+
    "\13\6\1\u0113\15\6\7\0\2\6\2\0\1\u0114\1\6"+
    "\3\0\31\6\7\0\2\6\2\0\2\6\3\0\10\6"+
    "\1\u0115\20\6\7\0\2\6\2\0\2\6\3\0\6\6"+
    "\1\u0116\22\6\7\0\2\6\2\0\2\6\3\0\21\6"+
    "\1\u0117\7\6\7\0\2\6\2\0\2\6\3\0\13\6"+
    "\1\u0118\15\6\7\0\2\6\2\0\2\6\3\0\15\6"+
    "\1\u0119\13\6\7\0\2\6\2\0\2\6\3\0\10\6"+
    "\1\u011a\20\6\7\0\2\6\2\0\2\6\3\0\11\6"+
    "\1\u011b\17\6\7\0\2\6\2\0\2\6\3\0\21\6"+
    "\1\u011c\7\6\7\0\2\6\2\0\2\6\3\0\11\6"+
    "\1\u011d\17\6\7\0\2\6\2\0\2\6\3\0\1\u011e"+
    "\30\6\7\0\2\6\2\0\2\6\3\0\15\6\1\u011f"+
    "\13\6\7\0\2\6\2\0\2\6\3\0\15\6\1\u0120"+
    "\1\u0121\12\6\7\0\2\6\2\0\2\6\3\0\6\6"+
    "\1\u0122\22\6\7\0\2\6\2\0\2\6\3\0\10\6"+
    "\1\u0123\20\6\7\0\2\6\2\0\2\6\3\0\15\6"+
    "\1\u0124\13\6\7\0\2\6\2\0\2\6\3\0\5\6"+
    "\1\u0125\23\6\7\0\2\6\2\0\2\6\3\0\10\6"+
    "\1\u0126\20\6\7\0\2\6\2\0\2\6\3\0\15\6"+
    "\1\u0127\13\6\7\0\2\6\2\0\2\6\3\0\4\6"+
    "\1\u0128\24\6\7\0\2\6\2\0\2\6\3\0\11\6"+
    "\1\u0129\17\6\7\0\2\6\2\0\2\6\3\0\5\6"+
    "\1\u012a\23\6\7\0\2\6\2\0\2\6\3\0\1\6"+
    "\1\u012b\27\6\7\0\1\6\1\u012c\2\0\2\6\3\0"+
    "\31\6\7\0\2\6\2\0\2\6\3\0\15\6\1\u012d"+
    "\13\6\7\0\2\6\2\0\2\6\3\0\1\6\1\u012e"+
    "\27\6\7\0\2\6\2\0\2\6\3\0\11\6\1\u012f"+
    "\17\6\7\0\2\6\2\0\2\6\3\0\1\u0130\30\6"+
    "\7\0\2\6\2\0\2\6\3\0\16\6\1\u0131\12\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\u0132\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\u0133\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\u0134\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\14\6\1\u0135\14\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\u0136\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\15\6\1\u0137\13\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\6\1\u0138\27\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\u0139\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\14\6\1\u013a\14\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\u013b\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\6\1\u013c\27\6"+
    "\7\0\2\6\2\0\2\6\3\0\15\6\1\u013d\13\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\u013e\2\6\1\u013f"+
    "\25\6\7\0\2\6\2\0\2\6\3\0\20\6\1\u0140"+
    "\10\6\7\0\2\6\2\0\2\6\3\0\13\6\1\u0141"+
    "\15\6\7\0\2\6\2\0\2\6\3\0\7\6\1\u0142"+
    "\21\6\7\0\2\6\2\0\2\6\3\0\26\6\1\u0143"+
    "\2\6\7\0\2\6\2\0\2\6\3\0\21\6\1\u0144"+
    "\7\6\7\0\2\6\2\0\2\6\3\0\10\6\1\u0145"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\11\6\1\u0146"+
    "\17\6\7\0\2\6\2\0\2\6\3\0\11\6\1\u0147"+
    "\17\6\7\0\2\6\2\0\2\6\3\0\1\6\1\u0148"+
    "\27\6\7\0\2\6\2\0\2\6\3\0\11\6\1\u0149"+
    "\17\6\7\0\2\6\2\0\2\6\3\0\14\6\1\u014a"+
    "\14\6\7\0\2\6\2\0\2\6\3\0\10\6\1\u014b"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\22\6\1\u014c"+
    "\6\6\7\0\2\6\2\0\2\6\3\0\11\6\1\u014d"+
    "\17\6\7\0\2\6\2\0\2\6\3\0\10\6\1\u014e"+
    "\4\6\1\u014f\13\6\7\0\2\6\2\0\2\6\3\0"+
    "\1\6\1\u0150\27\6\7\0\2\6\2\0\2\6\3\0"+
    "\16\6\1\u0151\12\6\7\0\2\6\2\0\2\6\3\0"+
    "\14\6\1\u0152\14\6\7\0\2\6\2\0\2\6\3\0"+
    "\11\6\1\u0153\17\6\7\0\2\6\2\0\2\6\3\0"+
    "\16\6\1\u0154\12\6\7\0\2\6\2\0\2\6\3\0"+
    "\1\u0155\30\6\7\0\2\6\2\0\2\6\3\0\5\6"+
    "\1\u0156\23\6\7\0\2\6\2\0\2\6\3\0\3\6"+
    "\1\u0157\25\6\7\0\2\6\2\0\2\6\3\0\3\6"+
    "\1\u0158\25\6\7\0\2\6\2\0\2\6\3\0\5\6"+
    "\1\u0159\23\6\7\0\2\6\2\0\2\6\3\0\3\6"+
    "\1\u015a\25\6\7\0\2\6\2\0\2\6\3\0\13\6"+
    "\1\u015b\15\6\7\0\2\6\2\0\2\6\3\0\16\6"+
    "\1\u015c\12\6\7\0\2\6\2\0\2\6\3\0\1\6"+
    "\1\u015d\27\6\7\0\2\6\2\0\1\u015e\1\6\3\0"+
    "\31\6\7\0\2\6\2\0\2\6\3\0\6\6\1\u015f"+
    "\22\6\7\0\2\6\2\0\2\6\3\0\14\6\1\u0160"+
    "\14\6\7\0\2\6\2\0\2\6\3\0\22\6\1\u0161"+
    "\6\6\7\0\2\6\2\0\2\6\3\0\10\6\1\u0162"+
    "\20\6\7\0\2\6\2\0\1\u0163\1\6\3\0\31\6"+
    "\7\0\2\6\2\0\2\6\3\0\4\6\1\u0164\24\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\u0165\30\6\7\0"+
    "\2\6\2\0\1\u0166\1\6\3\0\31\6\7\0\2\6"+
    "\2\0\2\6\3\0\7\6\1\u0167\21\6\7\0\2\6"+
    "\2\0\2\6\3\0\2\6\1\u0168\26\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\u0169\20\6\7\0\2\6"+
    "\2\0\2\6\3\0\1\6\1\u016a\27\6\7\0\2\6"+
    "\2\0\2\6\3\0\11\6\1\u016b\17\6\7\0\2\6"+
    "\2\0\2\6\3\0\14\6\1\u016c\14\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\u016d\20\6\7\0\2\6"+
    "\2\0\2\6\3\0\1\6\1\u016e\27\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\u016f\20\6\7\0\2\6"+
    "\2\0\2\6\3\0\11\6\1\u0170\17\6\7\0\2\6"+
    "\2\0\2\6\3\0\13\6\1\u0171\15\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\u0172\20\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\u0173\20\6\7\0\2\6"+
    "\2\0\2\6\3\0\2\6\1\u0174\26\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\u0175\20\6\7\0\2\6"+
    "\2\0\2\6\3\0\11\6\1\u0176\17\6\7\0\2\6"+
    "\2\0\2\6\3\0\10\6\1\u0177\20\6\7\0\2\6"+
    "\2\0\1\u0178\1\6\3\0\31\6\7\0\2\6\2\0"+
    "\2\6\3\0\15\6\1\u0179\13\6\7\0\2\6\2\0"+
    "\2\6\3\0\1\6\1\u017a\27\6\7\0\2\6\2\0"+
    "\2\6\3\0\22\6\1\u017b\6\6\7\0\2\6\2\0"+
    "\2\6\3\0\13\6\1\u017c\15\6\7\0\2\6\2\0"+
    "\2\6\3\0\11\6\1\u017d\17\6\7\0\2\6\2\0"+
    "\2\6\3\0\10\6\1\u017e\20\6\7\0\2\6\2\0"+
    "\2\6\3\0\11\6\1\u017f\17\6\7\0\2\6\2\0"+
    "\2\6\3\0\12\6\1\u0180\16\6\7\0\2\6\2\0"+
    "\2\6\3\0\5\6\1\u0181\23\6\7\0\2\6\2\0"+
    "\2\6\3\0\5\6\1\u0182\23\6\7\0\2\6\2\0"+
    "\1\u0183\1\6\3\0\31\6\7\0\2\6\2\0\2\6"+
    "\3\0\15\6\1\u0184\13\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\6\1\u0185\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\15\6\1\u0186\13\6\7\0\2\6\2\0\2\6"+
    "\3\0\15\6\1\u0187\13\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\6\1\u0188\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\6\1\u0189\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\6\1\u018a\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\21\6\1\u018b\7\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\6\1\u018c\27\6\7\0\2\6\2\0\2\6"+
    "\3\0\23\6\1\u018d\5\6\7\0\2\6\2\0\2\6"+
    "\3\0\13\6\1\u018e\15\6\7\0\2\6\2\0\2\6"+
    "\3\0\14\6\1\u018f\14\6\7\0\2\6\2\0\2\6"+
    "\3\0\15\6\1\u0190\13\6\7\0\2\6\2\0\2\6"+
    "\3\0\2\6\1\u0191\26\6\7\0\2\6\2\0\2\6"+
    "\3\0\10\6\1\u0192\20\6\7\0\2\6\2\0\2\6"+
    "\3\0\21\6\1\u0193\7\6\7\0\2\6\2\0\2\6"+
    "\3\0\14\6\1\u0194\14\6\7\0\2\6\2\0\2\6"+
    "\3\0\14\6\1\u0195\14\6\7\0\2\6\2\0\2\6"+
    "\3\0\14\6\1\u0196\14\6\7\0\2\6\2\0\2\6"+
    "\3\0\11\6\1\u0197\17\6\7\0\2\6\2\0\2\6"+
    "\3\0\11\6\1\u0198\17\6\7\0\2\6\2\0\2\6"+
    "\3\0\11\6\1\u0199\17\6\7\0\2\6\2\0\2\6"+
    "\3\0\1\u019a\30\6\7\0\2\6\2\0\2\6\3\0"+
    "\13\6\1\u019b\15\6\7\0\2\6\2\0\2\6\3\0"+
    "\11\6\1\u019c\17\6\7\0\2\6\2\0\2\6\3\0"+
    "\1\u019d\30\6\7\0\2\6\2\0\2\6\3\0\14\6"+
    "\1\u019e\14\6\7\0\2\6\2\0\2\6\3\0\15\6"+
    "\1\u019f\13\6\7\0\2\6\2\0\2\6\3\0\1\6"+
    "\1\u01a0\27\6\7\0\2\6\2\0\2\6\3\0\1\6"+
    "\1\u01a1\27\6\7\0\2\6\2\0\2\6\3\0\1\6"+
    "\1\u01a2\27\6\7\0\2\6\2\0\2\6\3\0\13\6"+
    "\1\u01a3\15\6\7\0\2\6\2\0\2\6\3\0\13\6"+
    "\1\u01a4\15\6\7\0\2\6\2\0\2\6\3\0\11\6"+
    "\1\u01a5\17\6\7\0\2\6\2\0\2\6\3\0\11\6"+
    "\1\u01a6\17\6\7\0\2\6\2\0\2\6\3\0\1\u01a7"+
    "\30\6\7\0\2\6\2\0\2\6\3\0\6\6\1\u01a8"+
    "\22\6\7\0\2\6\2\0\2\6\3\0\1\6\1\u01a9"+
    "\27\6\7\0\2\6\2\0\2\6\3\0\6\6\1\u01aa"+
    "\22\6\7\0\2\6\2\0\2\6\3\0\10\6\1\u01ab"+
    "\20\6\7\0\2\6\2\0\2\6\3\0\1\u01ac\30\6"+
    "\7\0\2\6\2\0\2\6\3\0\6\6\1\u01ad\22\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\u01ae\20\6"+
    "\7\0\2\6\2\0\2\6\3\0\15\6\1\u01af\13\6"+
    "\7\0\2\6\2\0\2\6\3\0\1\6\1\u01b0\27\6"+
    "\7\0\2\6\2\0\2\6\3\0\11\6\1\u01b1\17\6"+
    "\7\0\2\6\2\0\2\6\3\0\16\6\1\u01b2\12\6"+
    "\7\0\2\6\2\0\2\6\3\0\13\6\1\u01b3\15\6"+
    "\7\0\2\6\2\0\2\6\3\0\10\6\1\u01b4\20\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14883];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\3\11\25\1\4\0"+
    "\1\11\60\1\1\11\2\0\71\1\1\0\u0123\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[436];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _YangLexer() {
    this((java.io.Reader)null);
  }


  public _YangLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _YangLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return YANG_CASE;
          }
        case 77: break;
        case 64: 
          { return YANG_IF_FEATURE;
          }
        case 78: break;
        case 21: 
          { return YANG_PATH;
          }
        case 79: break;
        case 32: 
          { return YANG_STATUS;
          }
        case 80: break;
        case 30: 
          { return YANG_REFINE;
          }
        case 81: break;
        case 15: 
          { return YANG_LIST;
          }
        case 82: break;
        case 45: 
          { return YANG_DEFAULT;
          }
        case 83: break;
        case 8: 
          { return YANG_COMMENT;
          }
        case 84: break;
        case 62: 
          { return YANG_BELONGS_TO;
          }
        case 85: break;
        case 23: 
          { return YANG_RANGE;
          }
        case 86: break;
        case 37: 
          { return YANG_DELETE;
          }
        case 87: break;
        case 19: 
          { return YANG_BASE;
          }
        case 88: break;
        case 43: 
          { return YANG_CONTACT;
          }
        case 89: break;
        case 51: 
          { return YANG_IDENTITY;
          }
        case 90: break;
        case 13: 
          { return YANG_MUST;
          }
        case 91: break;
        case 49: 
          { return YANG_REVISION;
          }
        case 92: break;
        case 27: 
          { return YANG_ANYXML;
          }
        case 93: break;
        case 40: 
          { return YANG_REPLACE;
          }
        case 94: break;
        case 16: 
          { return YANG_USES;
          }
        case 95: break;
        case 53: 
          { return YANG_POSITION;
          }
        case 96: break;
        case 39: 
          { return YANG_AUGMENT;
          }
        case 97: break;
        case 72: 
          { return YANG_REVISION_DATE;
          }
        case 98: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 99: break;
        case 47: 
          { return YANG_PATTERN;
          }
        case 100: break;
        case 28: 
          { return YANG_MODULE;
          }
        case 101: break;
        case 26: 
          { return YANG_VALUE;
          }
        case 102: break;
        case 6: 
          { return YANG_LEFT_BRACE;
          }
        case 103: break;
        case 71: 
          { return YANG_ORGANIZATION;
          }
        case 104: break;
        case 24: 
          { return YANG_UNITS;
          }
        case 105: break;
        case 22: 
          { return YANG_WHEN;
          }
        case 106: break;
        case 31: 
          { return YANG_UNIQUE;
          }
        case 107: break;
        case 12: 
          { return YANG_KEY;
          }
        case 108: break;
        case 7: 
          { return YANG_RIGHT_BRACE;
          }
        case 109: break;
        case 25: 
          { return YANG_INPUT;
          }
        case 110: break;
        case 63: 
          { return YANG_ORDERED_BY;
          }
        case 111: break;
        case 4: 
          { return YANG_PLUS;
          }
        case 112: break;
        case 18: 
          { return YANG_TYPE;
          }
        case 113: break;
        case 74: 
          { return YANG_ERROR_MESSAGE;
          }
        case 114: break;
        case 35: 
          { return YANG_CONFIG;
          }
        case 115: break;
        case 61: 
          { return YANG_DEVIATION;
          }
        case 116: break;
        case 73: 
          { return YANG_ERROR_APP_TAG;
          }
        case 117: break;
        case 52: 
          { return YANG_PRESENCE;
          }
        case 118: break;
        case 17: 
          { return YANG_ENUM;
          }
        case 119: break;
        case 9: 
          { return YANG_ADD;
          }
        case 120: break;
        case 54: 
          { return YANG_NAMESPACE;
          }
        case 121: break;
        case 56: 
          { return YANG_LEAF_LIST;
          }
        case 122: break;
        case 5: 
          { return YANG_SEMICOLON;
          }
        case 123: break;
        case 57: 
          { return YANG_REFERENCE;
          }
        case 124: break;
        case 38: 
          { return YANG_PREFIX;
          }
        case 125: break;
        case 34: 
          { return YANG_IMPORT;
          }
        case 126: break;
        case 66: 
          { return YANG_DESCRIPTION;
          }
        case 127: break;
        case 3: 
          { return YANG_STRING;
          }
        case 128: break;
        case 70: 
          { return YANG_MIN_ELEMENTS;
          }
        case 129: break;
        case 46: 
          { return YANG_DEVIATE;
          }
        case 130: break;
        case 41: 
          { return YANG_TYPEDEF;
          }
        case 131: break;
        case 69: 
          { return YANG_MAX_ELEMENTS;
          }
        case 132: break;
        case 65: 
          { return YANG_YIN_ELEMENT;
          }
        case 133: break;
        case 14: 
          { return YANG_LEAF;
          }
        case 134: break;
        case 44: 
          { return YANG_FEATURE;
          }
        case 135: break;
        case 10: 
          { return YANG_RPC;
          }
        case 136: break;
        case 60: 
          { return YANG_CONTAINER;
          }
        case 137: break;
        case 36: 
          { return YANG_CHOICE;
          }
        case 138: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 139: break;
        case 55: 
          { return YANG_MANDATORY;
          }
        case 140: break;
        case 67: 
          { return YANG_NOTIFICATION;
          }
        case 141: break;
        case 76: 
          { return YANG_REQUIRE_INSTANCE;
          }
        case 142: break;
        case 75: 
          { return YANG_FRACTION_DIGITS;
          }
        case 143: break;
        case 11: 
          { return YANG_BIT;
          }
        case 144: break;
        case 42: 
          { return YANG_INCLUDE;
          }
        case 145: break;
        case 48: 
          { return YANG_ARGUMENT;
          }
        case 146: break;
        case 58: 
          { return YANG_EXTENSION;
          }
        case 147: break;
        case 68: 
          { return YANG_YANG_VERSION;
          }
        case 148: break;
        case 29: 
          { return YANG_LENGTH;
          }
        case 149: break;
        case 59: 
          { return YANG_SUBMODULE;
          }
        case 150: break;
        case 33: 
          { return YANG_OUTPUT;
          }
        case 151: break;
        case 50: 
          { return YANG_GROUPING;
          }
        case 152: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
